# Generated by Django 5.0.2 on 2024-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=255)),
                ("clubbed_name", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=255)),
                ("value", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
